export enum Computations {
    ALL_CATEGORIES = 'ALL_CATEGORIES',
    DEFAULT_CATEGORY = 'DEFAULT_CATEGORY',
    ALL_PEOPLE = 'ALL_PEOPLE',
    OUTSTANDING_BALANCE_AMOUNT = 'OUTSTANDING_BALANCE_AMOUNT',
    OUTSTANDING_BALANCE_PAYEE = 'OUTSTANDING_BALANCE_PAYEE',
}