import dotenv from "dotenv";

dotenv.config();

const {
    GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL,
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY,

    DISCORD_TOKEN,
    DISCORD_CLIENT_ID,

    DISCORD_GUILD_ID,
    DISCORD_CHANNEL_ID,

    GOOGLE_SHEETS_SPREADSHEET_ID,

    GEMINI_API_KEY,

    PURCHASES_SHEET_NAME = "Purchases",
    PURCHASES_COL_DATE = "Date",
    PURCHASES_COL_DESCRIPTION = "Purchase",
    PURCHASES_COL_AMOUNT = "Amount",
    PURCHASES_COL_CATEGORY = "Category",
    PURCHASES_COL_PAID_BY = "Paid By",
    PURCHASES_COL_SPLIT_TYPE = "Split",
    PURCHASES_COL_ID = "Transaction ID",

    SCHEDULED_PAYMENTS_SHEET_NAME = "Scheduled Payments",
    SCHEDULED_PAYMENTS_COL_DISABLED = "Disabled",
    SCHEDULED_PAYMENTS_COL_DESCRIPTION = "Purchase",
    SCHEDULED_PAYMENTS_COL_AMOUNT = "Amount",
    SCHEDULED_PAYMENTS_COL_CATEGORY = "Category",
    SCHEDULED_PAYMENTS_COL_PAID_BY = "Paid By",
    SCHEDULED_PAYMENTS_COL_FREQUENCY = "Frequency",
    SCHEDULED_PAYMENTS_COL_SPLIT = "Split",
    SCHEDULED_PAYMENTS_COL_LAST_PAID = "Last Paid",

    PREFERENCES_SHEET_NAME = "Preferences",
    PREFERENCES_COL_NAME = "Name",
    PREFERENCES_COL_DESCRIPTION = "Description",
    PREFERENCES_COL_VALUE = "Value",

    COMPUTATIONS_SHEET_NAME = "Computations",
    COMPUTATIONS_COL_NAME = "Name",
    COMPUTATIONS_COL_DESCRIPTION = "Description",
    COMPUTATIONS_COL_VALUE = "Value",

    SPLIT_TYPE_HALF = "50/50",
    SPLIT_TYPE_FULL = "Paid in full by other",

    TIMEZONE_OFFSET = -4,
    SCHEDULED_PAYMENTS_HOUR_TO_EXECUTE = 9,
    OUTSTANDING_BALANCE_REMINDER_HOUR_TO_EXECUTE = 11
} = process.env;

if (
    !GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL ||
    !GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY ||
    !DISCORD_TOKEN ||
    !DISCORD_CLIENT_ID ||
    !GOOGLE_SHEETS_SPREADSHEET_ID
) {
    throw new Error("Missing required environment variables");
}

const privateKeyModified = GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY.replace(
    /\\n/g,
    "\n"
);

export const config = {
    GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL,
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: privateKeyModified,
    DISCORD_TOKEN,
    DISCORD_CLIENT_ID,
    DISCORD_GUILD_ID,
    DISCORD_CHANNEL_ID,
    GEMINI_API_KEY,
    GOOGLE_SHEETS_SPREADSHEET_ID,
    PURCHASES_SHEET_NAME,
    PURCHASES_COL_DATE,
    PURCHASES_COL_DESCRIPTION,
    PURCHASES_COL_AMOUNT,
    PURCHASES_COL_CATEGORY,
    PURCHASES_COL_PAID_BY,
    PURCHASES_COL_SPLIT_TYPE,
    PURCHASES_COL_ID,
    SCHEDULED_PAYMENTS_SHEET_NAME,
    SCHEDULED_PAYMENTS_COL_DISABLED,
    SCHEDULED_PAYMENTS_COL_DESCRIPTION,
    SCHEDULED_PAYMENTS_COL_AMOUNT,
    SCHEDULED_PAYMENTS_COL_CATEGORY,
    SCHEDULED_PAYMENTS_COL_PAID_BY,
    SCHEDULED_PAYMENTS_COL_FREQUENCY,
    SCHEDULED_PAYMENTS_COL_SPLIT,
    SCHEDULED_PAYMENTS_COL_LAST_PAID,
    PREFERENCES_SHEET_NAME,
    PREFERENCES_COL_NAME,
    PREFERENCES_COL_DESCRIPTION,
    PREFERENCES_COL_VALUE,
    COMPUTATIONS_SHEET_NAME,
    COMPUTATIONS_COL_NAME,
    COMPUTATIONS_COL_DESCRIPTION,
    COMPUTATIONS_COL_VALUE,
    SPLIT_TYPE_HALF,
    SPLIT_TYPE_FULL,
    TIMEZONE_OFFSET,
    SCHEDULED_PAYMENTS_HOUR_TO_EXECUTE,
    OUTSTANDING_BALANCE_REMINDER_HOUR_TO_EXECUTE
};
